AllCops:
  TargetRubyVersion: 2.0
  Include:
    - "Gemfile"
  Exclude:
    - "gemfiles/vendor/**/*"
    - "perf/benchmark.rb"
    - "spec/support/apps/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/FormatString:
  EnforcedStyle: sprintf

Metrics/MethodLength:
  Max: 15
