test:
  adapter: <%= RUBY_PLATFORM == "java" ? "jdbcsqlite3" : "sqlite3" %>
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: <%= RUBY_PLATFORM == "java" ? "jdbcsqlite3" : "sqlite3" %>
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
